name: 'Photo Adventures '
favicon: null
layout_spectrum: 0.25974
typography_spectrum: 0.80212
title: Photo Galleries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040404'
    - '#404040'
    - '#808080'
    - '#aaaaaa'
  brandStrength: 0.6875
  lightness: 0.0625
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
