name: 'Photo Adventures '
favicon: null
layout_spectrum: 0
typography_spectrum: 0.80212
title: Adventures in Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040404'
    - '#404040'
    - '#808080'
    - '#aaaaaa'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
